name: Push to branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Execute commands
        run: |
          yarn || echo "yarn failed"
          mkdir apks || echo "mkdir failed"
          wget `node app.js` -O apks/wdbible.apk || echo "wget failed"

      - name: Commit and push if changes
        run: |
          git add -A
          git diff --quiet && git diff --staged --quiet || (git config --local user.email "action@github.com" && git config --local user.name "GitHub Action" && git commit -m 'Auto update from github actions' && git remote set-url origin https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/lisk809/wdbible.git && git push origin HEAD)
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
