name: Push to branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Execute commands
      run: |
        yarn
        node app.js
        rm -rf apks/*
        wget `cat url.txt` -O dist/apks/wdbible.apk

    - name: Commit and push if changes
      run: |
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m 'Auto update from github actions' && git push origin HEAD)
