name: Push to branch

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Execute commands
        run: |
          yarn || echo "yarn failed"
          mkdir apks || echo "mkdir failed"
          wget `node app.js` -O apks/wdbible.apk || echo "wget failed"

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git add -A
          git commit -m 'Auto update from github actions' && git push origin main
        env:
              MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
